const express = require("express");
const router = express.Router();
const header = require("./header");
const banner = require("./banner");
const popularCategory = require("./popular_category");
const specialDish = require("./special_dish");
const testimonial = require("./testimonial");
const ourStory = require("./our_story");
const footer = require("./footer");
router.use("/header", header);
router.use("/banner", banner);
router.use("/popular-category", popularCategory);
router.use("/special-dish", specialDish);
router.use("/testimonial", testimonial);
router.use("/our-story", ourStory);
router.use("/footer", footer);
module.exports = router;
